### ISSUE TITLE
Nova 4 compatibility?

### ISSUE THREAD

**Issue by scramatte** [dcasia/expandable-table-row#1]
Hello,

I've installed this package on my Nova 4 but  I don't see any change on the index page.
Can you give me an hand?

Regards

**Comment by milewski** [comment]
Did you call `->expandableRowData()`? This function expect you to return a field that will be shown bellow the field when the row is expanded


And make sure you are calling it on the fields that are shown on the index, it does nothing on details or form.

**Comment by scramatte** [comment]
This is my field definition.
I've tried on very simple resource too and nothing, the expandable content doesn't appears 

```php
            ...
            Text::make(__('billing.handle'), 'handle')
              ->size('w-full md:w-1/5 xl:w-1/4')
              ->exceptOnForms()
              ->asHtml()
              ->sortable()
              ->expandableRowData(function () {
                return Stack::make('_', [
                    Line::make(null)->displayUsing(fn() => 'Name')->asSubTitle(),
                    Text::make('Email')->copyable(),
                ]);
              }),
              ...
```

**Comment by milewski** [comment]
I suspect again you might have another package preventing you from using this package... If you can try on a blank nova project and add your package one by one you will be able to figure out which one causes the issue...

**Comment by milewski** [comment]
I just tested your code snipped locally and it works, I don't know where that ->size() method came from, I guess it might be a custom package and that is what causing the issue with this package:

![image](https://github.com/dcasia/expandable-table-row/assets/2874967/3160e4d2-fa30-4df7-991c-8cb75a8a498a)

**Comment by scramatte** [comment]
Hi,
On another Nova instance it works, so I'm going to investigate which package cause the problem.
->size() is related to a grid package for forms, on index it should be ok. Moreover other instance has same package and works properly.

I come back to you asap

Regards

**Comment by scramatte** [comment]
Hi,

After rebuild locally,  the problem is that in mounted method , "this._.type?.__file" never match  ResourceTableRow.vue on my instance.  It detects lots of components but  never  ResourceTableRow.vue.

In the  inspector list  I see a lot of components with this._.type?.__file = "undefined"  

Any idea ?

**Comment by milewski** [comment]
That must be because some other package overrode your original `ResourceTableRow.vue` file...  you can search within your vendor folder for something like `app.component('ResourceTableRow',` or `component("ResourceTableRow"` to try to find out which package is it..

**Comment by scramatte** [comment]
Thank you,  I've find the broken component ! The issue is due too 
https://github.com/outl1ne/nova-sortable

If you override component , it should have a similar name isn't it?
Does is not posible to look at  component name itself instead of filename?

Regards

**Comment by milewski** [comment]
You can see here he overrode that component but didn't add a name to it: https://github.com/outl1ne/nova-sortable/blob/main/resources/js/components/ResourceTableRow.vue#L226-L228 the original component also doesn't have a name, 


Perhaps what could be done is try to monkey-patch the app.component function to intercept when any component named `ResourceTableRow` is being registered and wrap it: https://github.com/outl1ne/nova-sortable/blob/main/resources/js/entry.js#L27C55-L27C55, similar to what I have done in this other package: https://github.com/dcasia/nova-mega-filter/blob/cc7bc0df94e79f6d97ed4fbd970d93c983ff8e49/resources/js/card.js#L6-L16

**Comment by scramatte** [comment]
I'm trying what you told me  but my problem is that  ResourceTableRow is mounted every time  I reorder line.
Reorder is inccorrect and I think that is due to that vNode is recreated  on evert sort.

**Comment by milewski** [comment]
Well I will try to make an alternative version of that sortable package sometime next week, I feel like there is no need to override so many files and have so many lines of code... and without overriding any nova files, but perhaps I will have fewer feature.. like no move to top/move to bottom ... etc since those are option I never use / click

**Comment by scramatte** [comment]
I don't need  move to top or move to bottom.  A new package will be great.
What I think that is missing too is something to resize columns and define width

**Comment by scramatte** [comment]
By the way I think  that If you will add drag handle into the checkbox td container, into the expandable-table-row package   you shouldn't remove on unmount the checkbox container itself , instead you should remove the toggler dom element if it possible. 

Currently I've only override ResourceTable  component.  One component instead of 4 ... 
NovaSortable use VueDraggableNext and draggable container is "tbody" and they achieve it into ResourceTable component.

**Comment by scramatte** [comment]
The problem of the reorder is due to new lines that create  ExpandableTableRow package.  You need to wrap the current line and the expandable line into a tbody. I've practically get it working...

**Comment by scramatte** [comment]
Hi

Finally I get it working It was required to make a small change into your ExpandableTableRow 

![imagen](https://github.com/dcasia/expandable-table-row/assets/188766/59998a05-ab9f-4129-82f1-02dd882accec)

About NovaSortable,  Is still need to override ResourceTableVue.vue , I will commit the changes to my repositories. Might be you can take a look to see if it possible to avoid this dependency.

Regards
