### ISSUE TITLE
Feature request:  fill using ajax  and buttons

### ISSUE THREAD

**Issue by scramatte** [dcasia/expandable-table-row#6]
Hi, 

It would be nice to add feature to fill the expandable row from ajax query  and buttons

Regards

**Comment by milewski** [comment]
I think this might be out of the scope of this package.. but this is achievable by making a custom field that fetch data when it is mounted ... so you could have something like this:

```php
Text::make('XXX'')
    ->expandableRowData(function () {
        return [
            MyCustonAjaxField::make(),
        ];
    }),
```

and the `MyCustonAjaxField` renders the data with whatever look you like...

**Comment by scramatte** [comment]
Good idea, thank you
